#!/usr/bin/env python3
"""Generate the Claude Code plugin marketplace from this checkout.

Writes .claude-plugin/marketplace.json, plugins/router (hooks, CLI, dispatch skill, the
tier agents) and plugins/shared-roles (the nine base roles). Every file is a copy, never a
symlink; files nobody generates are removed. --check compares and writes nothing: exit 1
names the first drifted path, exit 0 when every generated byte matches.
Standard library only; no network.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
OWNER = {"name": "AEIA", "url": "https://aeia.dev"}
REPOSITORY = "https://github.com/aeiadev/router"
MANAGED = (".claude-plugin", "plugins")
CODEX_ONLY = frozenset(("codex_spawn_guard.py",))  # Plugins are Claude Code only.
SCRIPT = re.compile(r'python3 "\$HOME/\.claude/hooks/router/([a-z_]+\.py)"')
GUARD = ('[ -e "${{CLAUDE_HOME:-$HOME/.claude}}/router/install-manifest.json" ] || '
         'python3 "${{CLAUDE_PLUGIN_ROOT}}/hooks/router/{script}"')
ROUTER_DESCRIPTION = ("Routing hooks, tier agents, the dispatch skill and the router command: bounded "
                      "subagent tasks go to the model that fits them and each result to a fresh judge.")
SHARED_DESCRIPTION = ("Nine base agent roles: sweeper, researcher, planner, builder, builder-in-place, "
                      "judge, worker, test-writer and docs-writer.")


def as_json(value):
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def ignored(relative):
    """Bytecode is never generated and never tracked."""
    return "__pycache__" in Path(relative).parts or relative.endswith(".pyc")


def source(relative):
    path = ROOT / relative
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"missing source file: {relative}")
    return path.read_bytes(), bool(path.stat().st_mode & 0o100)


def shared_roles():
    """The nine base roles pinned in agents/SHARED.sha256, checked against those pins."""
    names = []
    for line in (ROOT / "agents/SHARED.sha256").read_text(encoding="utf-8").splitlines():
        digest, _, name = line.partition("  ")
        if "/" in name:
            continue  # Codex roles and scripts are pinned here too; they are not plugin roles.
        data, _ = source(f"agents/{name}")
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError(f"agents/{name} differs from agents/SHARED.sha256; fix the role or its pin first")
        names.append(name)
    return sorted(names)


def tier_agents():
    """Every tier agent the route table names: the Router plugin ships exactly these."""
    routes = json.loads((ROOT / "hooks/router/routes.json").read_text(encoding="utf-8"))
    return sorted({f"{spec['agent']}.md" for levels in routes["tiers"].values() for spec in levels.values()})


def plugin_hooks():
    """The script install's hook registrations, each behind the stand-down guard."""
    example = json.loads((ROOT / "examples/settings.example.json").read_text(encoding="utf-8"))
    hooks = {}
    for event, blocks in example["hooks"].items():
        hooks[event] = []
        for block in blocks:
            entries = []
            for hook in block["hooks"]:
                match = SCRIPT.fullmatch(hook["command"])
                if match is None:
                    raise ValueError(f"unexpected hook command in examples/settings.example.json: {event}")
                entries.append({"type": "command", "command": GUARD.format(script=match.group(1))})
            hooks[event].append({**{key: value for key, value in block.items() if key != "hooks"}, "hooks": entries})
    return {"hooks": hooks}


def expected():
    """Relative path -> (bytes, executable) for every generated file."""
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    files = {
        ".claude-plugin/marketplace.json": (as_json({"name": "router", "owner": OWNER, "plugins": [
            {"name": "router", "source": "./plugins/router"},
            {"name": "shared-roles", "source": "./plugins/shared-roles"}]}), False),
        "plugins/router/.claude-plugin/plugin.json": (as_json({
            "name": "router", "version": version, "description": ROUTER_DESCRIPTION, "author": OWNER,
            "homepage": REPOSITORY, "repository": REPOSITORY, "license": "MIT"}), False),
        "plugins/router/hooks/hooks.json": (as_json(plugin_hooks()), False),
        "plugins/router/bin/router": (source("bin/router")[0], True),
        "plugins/shared-roles/.claude-plugin/plugin.json": (as_json({
            "name": "shared-roles", "version": version, "description": SHARED_DESCRIPTION, "author": OWNER,
            "license": "MIT"}), False),
    }
    for path in sorted((ROOT / "hooks/router").iterdir()):
        if path.name not in CODEX_ONLY and not ignored(f"hooks/router/{path.name}") and not path.is_dir():
            files[f"plugins/router/hooks/router/{path.name}"] = source(f"hooks/router/{path.name}")
    for path in sorted((ROOT / "skills/dispatch").rglob("*")):
        relative = path.relative_to(ROOT / "skills/dispatch").as_posix()
        if not path.is_dir() and not ignored(relative):
            files[f"plugins/router/skills/dispatch/{relative}"] = source(f"skills/dispatch/{relative}")
    for name in tier_agents():
        files[f"plugins/router/agents/{name}"] = (source(f"agents/{name}")[0], False)
    for name in shared_roles():
        files[f"plugins/shared-roles/agents/{name}"] = (source(f"agents/{name}")[0], False)
    return files


def actual():
    """Relative path -> lstat result for every entry under the managed folders, directories included."""
    found = {}
    for folder in MANAGED:
        for base, folders, names in os.walk(ROOT / folder):
            folders[:] = [name for name in folders if name != "__pycache__" and not (Path(base) / name).is_symlink()]
            for name in folders:
                found[(Path(base) / name).relative_to(ROOT).as_posix()] = (Path(base) / name).lstat()
            for name in names + [name for name in os.listdir(base) if (Path(base) / name).is_symlink()
                                 and (Path(base) / name).is_dir()]:
                relative = (Path(base) / name).relative_to(ROOT).as_posix()
                if not ignored(relative):
                    found[relative] = (Path(base) / name).lstat()
    return found


def drift(wanted, present):
    """(path, kind) for every generated path that differs, in path order."""
    result = []
    folders = {parent.as_posix() for relative in wanted for parent in Path(relative).parents}
    for relative in sorted(set(wanted) | set(present)):
        if relative in folders and relative in present and stat.S_ISDIR(present[relative].st_mode):
            continue
        if relative not in present:
            result.append((relative, "missing"))
        elif relative not in wanted:
            result.append((relative, "extra"))
        elif stat.S_ISLNK(present[relative].st_mode):
            result.append((relative, "symlink"))
        elif not stat.S_ISREG(present[relative].st_mode):
            result.append((relative, "not a file"))
        else:
            data, executable = wanted[relative]
            if (ROOT / relative).read_bytes() != data or bool(present[relative].st_mode & 0o100) != executable:
                result.append((relative, "changed"))
    return result


def write(relative, data, executable):
    path = ROOT / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=".gen-", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
        os.chmod(temporary, 0o755 if executable else 0o644)
        if path.is_symlink() or (path.exists() and not path.is_file()):
            path.unlink()
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def prune():
    """Remove empty directories left under the managed folders, deepest first."""
    for folder in MANAGED:
        for base, folders, names in sorted(os.walk(ROOT / folder), key=lambda row: -len(Path(row[0]).parts)):
            if base != str(ROOT / folder) and not os.listdir(base):
                os.rmdir(base)


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 naming the first drifted path; write nothing")
    args = parser.parse_args(argv)
    try:
        wanted = expected()
        changes = drift(wanted, actual())
        if args.check:
            if changes:
                relative, kind = changes[0]
                sys.exit(f"gen_plugin: drift at {relative} ({kind}); run python3 scripts/gen_plugin.py")
            print(f"gen_plugin: {len(wanted)} generated files match")
            return 0
        written = removed = 0
        for relative, kind in changes:
            path = ROOT / relative
            if kind == "extra":
                if not path.is_dir() or path.is_symlink():
                    path.unlink()
                removed += 1
            else:
                write(relative, *wanted[relative])
                written += 1
        prune()
        print(f"gen_plugin: {len(wanted)} generated files ({written} written, {removed} removed)")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        sys.exit(f"gen_plugin: {exc}")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
