#!/usr/bin/env python3
"""Generate Router tiers and Codex TOMLs from the shared Markdown roles."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]


def parse(text):
    match = re.fullmatch(r"---\n(.*?)\n---\n(.*)", text, re.DOTALL)
    if not match:
        raise ValueError("expected Markdown frontmatter")
    metadata = {}
    for line in match[1].splitlines():
        key, value = line.split(": ", 1)
        if key in metadata:
            raise ValueError("duplicate frontmatter field: " + key)
        metadata[key] = value
    return metadata, match[2]


def toml(metadata, body, models, shared=False):
    pin = models[metadata["model"]]
    values = dict(name=metadata["name"], description=metadata["description"],
                  developer_instructions=body.strip() + "\n",
                  model=pin["model"], model_reasoning_effort=pin["effort"])
    # Preserve Harness's byte format for the shared base TOMLs.
    generator = "codex/generate_agents.py" if shared else "scripts/generate_roles.py"
    return f"# Generated by {generator}; edit installed defaults as needed.\n" + "".join(
        f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in values.items())


def expected(root):
    routes = json.loads((root / "hooks/router/routes.json").read_text())
    bases = {}
    for row in (root / "agents/SHARED.sha256").read_text().splitlines():
        digest, name = row.split()
        path = root / "agents" / name
        payload = path.read_bytes()
        if hashlib.sha256(payload).hexdigest() != digest:
            raise ValueError(f"shared role drift: agents/{name}")
        metadata, body = parse(payload.decode("utf-8"))
        if metadata["name"] != path.stem:
            raise ValueError(f"role name differs from filename: {name}")
        bases[path.stem] = (metadata, body)
    wanted = {}
    for base, (metadata, body) in bases.items():
        wanted[f"codex/agents/{base}.toml"] = toml(metadata, body, routes["codex_models"], shared=True)
        for tier, spec in routes["tiers"].get(base, {}).items():
            source = routes["tier_sources"][base]
            if source["source"] != f"agents/{base}.md":
                raise ValueError(f"unexpected tier source for {base}")
            fields = dict(metadata, name=spec["agent"], description=f"Tier of {base}", model=spec["model"])
            if spec["effort"] == "none":
                fields.pop("effort", None)
            else:
                fields["effort"] = spec["effort"]
            wanted[f"agents/{spec['agent']}.md"] = "---\n" + "".join(
                f"{key}: {value}\n" for key, value in fields.items()) + "---\n" + body
            wanted[f"codex/agents/{spec['agent']}.toml"] = toml(fields, body, routes["codex_models"])
    return bases, wanted


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on missing, extra, or changed generated files")
    args = parser.parse_args()
    try:
        bases, wanted = expected(ROOT)
        actual = {str(path.relative_to(ROOT)) for folder, suffix in (("agents", "*.md"), ("codex/agents", "*.toml"))
                  for path in (ROOT / folder).glob(suffix)} - {f"agents/{base}.md" for base in bases}
        extra = actual - wanted.keys()
        drift = [name for name, text in wanted.items()
                 if not (ROOT / name).is_file() or (ROOT / name).read_text() != text]
        if extra or (args.check and drift):
            sys.exit("Role drift: " + ", ".join(sorted(extra | set(drift))) + "; run python3 scripts/generate_roles.py")
        if not args.check:
            for name, text in wanted.items():
                (ROOT / name).parent.mkdir(parents=True, exist_ok=True)
                (ROOT / name).write_text(text, encoding="utf-8")
        print(f"PASS: {len(bases)} shared roles and {len(wanted)} generated files match")
    except (OSError, ValueError, KeyError) as exc:
        sys.exit(str(exc))


if __name__ == "__main__":
    main()
